#!/usr/bin/env bash
# Generates credentials for HomeLab stacks and saves them to Ansible Vault.
# Usage: ./scripts/generate-credentials.sh <stack>
# Stacks: common, networking, management, media, semaphore, all
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VAULT_FILE="${REPO_ROOT}/ansible/group_vars/all/vault.yml"
STACK="${1:?Usage: $0 <stack>  (available: common, networking, management, media, semaphore, all)}"

# --- Vault password handling ---
read -s -p "Vault password: " VAULT_PASS
echo

VAULT_PASS_FILE=$(mktemp)
TMPFILE=$(mktemp)
chmod 600 "$VAULT_PASS_FILE" "$TMPFILE"
echo "$VAULT_PASS" > "$VAULT_PASS_FILE"
trap 'rm -f "$VAULT_PASS_FILE" "$TMPFILE"' EXIT

# Decrypt or initialize vault
if [ -f "$VAULT_FILE" ]; then
    if head -1 "$VAULT_FILE" | grep -q '^\$ANSIBLE_VAULT'; then
        if ! ansible-vault view "$VAULT_FILE" --vault-password-file="$VAULT_PASS_FILE" > "$TMPFILE" 2>/dev/null; then
            echo "Error: Failed to decrypt vault. Wrong password?"
            exit 1
        fi
    else
        cp "$VAULT_FILE" "$TMPFILE"
    fi
else
    echo "# Ansible Vault secrets" > "$TMPFILE"
    echo "# Generated by scripts/generate-credentials.sh" >> "$TMPFILE"
fi

# --- Helper functions ---

generate_password() {
    openssl rand -base64 48 | tr -dc 'a-zA-Z0-9' | head -c "${1:-32}"
}

var_exists() {
    grep -q "^${1}:" "$TMPFILE"
}

get_var() {
    grep "^${1}:" "$TMPFILE" | sed 's/^[^:]*: *"\{0,1\}\([^"]*\)"\{0,1\}/\1/'
}

# Check if variable is unset (missing or has REPLACE_ placeholder)
var_needs_value() {
    local name="$1"
    if ! var_exists "$name"; then
        return 0
    fi
    local current
    current=$(get_var "$name")
    [[ "$current" == REPLACE_* ]]
}

# Set a vault variable. Returns 1 if variable already has a real value.
set_var() {
    local name="$1" value="$2"
    if var_exists "$name"; then
        local current
        current=$(get_var "$name")
        if [[ "$current" != REPLACE_* ]]; then
            return 1  # already set
        fi
        # Remove placeholder line, then append new value
        grep -v "^${name}:" "$TMPFILE" > "${TMPFILE}.new"
        mv "${TMPFILE}.new" "$TMPFILE"
    fi
    printf '%s: "%s"\n' "$name" "$value" >> "$TMPFILE"
    return 0
}

# Prompt user for a value with optional default
prompt_value() {
    local prompt="$1" default="${2:-}"
    local value
    if [ -n "$default" ]; then
        read -p "${prompt} [${default}]: " value
        echo "${value:-$default}"
    else
        while true; do
            read -p "${prompt}: " value
            if [ -n "$value" ]; then
                echo "$value"
                return
            fi
            echo "  Value required." >&2
        done
    fi
}

# Prompt for sensitive value (hidden input)
prompt_secret() {
    local prompt="$1"
    local value
    while true; do
        read -s -p "${prompt}: " value
        echo >&2  # newline after hidden input
        if [ -n "$value" ]; then
            echo "$value"
            return
        fi
        echo "  Value required." >&2
    done
}

CHANGED=false

# --- Stack functions ---

generate_common() {
    echo ""
    echo "=== Common Settings ==="
    echo ""

    if var_needs_value vault_domain || [[ "$(get_var vault_domain 2>/dev/null)" == "example.com" ]]; then
        local domain
        domain=$(prompt_value "Domain name (e.g. example.com)")
        set_var vault_domain "$domain" || true
        CHANGED=true
    else
        echo "  vault_domain: $(get_var vault_domain) (exists, skipping)"
    fi

    if var_needs_value vault_server_ip || [[ "$(get_var vault_server_ip 2>/dev/null)" == "192.168.1.100" ]]; then
        local server_ip
        server_ip=$(prompt_value "Server LAN IP" "192.168.68.82")
        set_var vault_server_ip "$server_ip" || true
        CHANGED=true
    else
        echo "  vault_server_ip: $(get_var vault_server_ip) (exists, skipping)"
    fi

    if var_needs_value vault_le_email; then
        local le_email
        le_email=$(prompt_value "Let's Encrypt email")
        set_var vault_le_email "$le_email" || true
        CHANGED=true
    else
        echo "  vault_le_email: $(get_var vault_le_email) (exists, skipping)"
    fi

    # Default VPN provider
    if var_needs_value vault_vpn_service_provider; then
        set_var vault_vpn_service_provider "pia" || true
        CHANGED=true
        echo "  vault_vpn_service_provider: pia (default)"
    fi
}

generate_networking() {
    echo ""
    echo "=== Networking Stack (Traefik + Cloudflare) ==="
    echo ""

    # Traefik dashboard password (auto-generated)
    if var_needs_value vault_traefik_dashboard_password; then
        local traefik_pass htpasswd_hash
        traefik_pass=$(generate_password 24)

        # Generate htpasswd hash — prefer local htpasswd, fall back to Docker
        if command -v htpasswd &>/dev/null; then
            htpasswd_hash=$(htpasswd -nbB admin "$traefik_pass")
        else
            htpasswd_hash=$(docker run --rm httpd:alpine htpasswd -nbB admin "$traefik_pass" 2>/dev/null)
        fi

        set_var vault_traefik_dashboard_password "$htpasswd_hash" || true
        CHANGED=true

        echo "  Traefik dashboard:"
        echo "    Username: admin"
        echo "    Password: ${traefik_pass}"
        echo ""
        echo "  Save this password — it is only shown once."
        echo ""
    else
        echo "  Traefik dashboard password: (exists, skipping)"
    fi

    # Cloudflare API email
    if var_needs_value vault_cf_api_email; then
        local cf_email
        cf_email=$(prompt_value "Cloudflare account email")
        set_var vault_cf_api_email "$cf_email" || true
        CHANGED=true
    else
        echo "  vault_cf_api_email: $(get_var vault_cf_api_email) (exists, skipping)"
    fi

    # Cloudflare DNS API token
    if var_needs_value vault_cf_dns_api_token; then
        local cf_token
        cf_token=$(prompt_secret "Cloudflare DNS API token")
        set_var vault_cf_dns_api_token "$cf_token" || true
        CHANGED=true
    else
        echo "  vault_cf_dns_api_token: (exists, skipping)"
    fi
}

generate_management() {
    echo ""
    echo "=== Management Stack (AdGuard + Uptime Kuma) ==="
    echo ""

    if var_needs_value adguard_username; then
        local adguard_pass
        adguard_pass=$(generate_password 24)
        set_var adguard_username "admin" || true
        set_var adguard_password "$adguard_pass" || true
        CHANGED=true

        echo "  AdGuard Home:"
        echo "    Username: admin"
        echo "    Password: ${adguard_pass}"
        echo ""
        echo "  Save this password — it is only shown once."
        echo ""
    else
        echo "  AdGuard credentials: (exist, skipping)"
    fi

    if var_needs_value vault_uptime_kuma_username; then
        local kuma_pass
        kuma_pass=$(generate_password 24)
        set_var vault_uptime_kuma_username "admin" || true
        set_var vault_uptime_kuma_password "$kuma_pass" || true
        CHANGED=true

        echo "  Uptime Kuma:"
        echo "    Username: admin"
        echo "    Password: ${kuma_pass}"
        echo ""
        echo "  Save this password — it is only shown once."
        echo ""
    else
        echo "  Uptime Kuma credentials: (exist, skipping)"
    fi
}

generate_media() {
    echo ""
    echo "=== Media Stack (VPN + qBittorrent + Jellyseerr + Cloudflare Tunnel) ==="
    echo ""

    # VPN credentials (user-provided)
    if var_needs_value vault_openvpn_user; then
        local vpn_user vpn_pass
        vpn_user=$(prompt_value "VPN (PIA) username")
        vpn_pass=$(prompt_secret "VPN (PIA) password")
        set_var vault_openvpn_user "$vpn_user" || true
        set_var vault_openvpn_password "$vpn_pass" || true
        CHANGED=true
    else
        echo "  VPN credentials: (exist, skipping)"
    fi

    # Cloudflare tunnel token (user-provided)
    if var_needs_value vault_cloudflare_tunnel_token; then
        local tunnel_token
        tunnel_token=$(prompt_secret "Cloudflare tunnel token")
        set_var vault_cloudflare_tunnel_token "$tunnel_token" || true
        CHANGED=true
    else
        echo "  Cloudflare tunnel token: (exists, skipping)"
    fi

    # qBittorrent credentials (auto-generated)
    if var_needs_value qbittorrent_username; then
        local qbt_pass
        qbt_pass=$(generate_password 24)
        set_var qbittorrent_username "admin" || true
        set_var qbittorrent_password "$qbt_pass" || true
        CHANGED=true

        echo "  qBittorrent:"
        echo "    Username: admin"
        echo "    Password: ${qbt_pass}"
        echo ""
        echo "  Save this password — it is only shown once."
        echo ""
    else
        echo "  qBittorrent credentials: (exist, skipping)"
    fi

    # Jellyfin admin (used by Jellyseerr role + future Jellyfin role)
    if var_needs_value vault_jellyfin_username; then
        echo ""
        echo "  Jellyfin admin credentials:"
        local jf_user jf_email jf_pass
        jf_user=$(prompt_value "Jellyfin username")
        jf_email=$(prompt_value "Jellyfin email")
        jf_pass=$(prompt_secret "Jellyfin password")
        set_var vault_jellyfin_username "$jf_user" || true
        set_var vault_jellyfin_email "$jf_email" || true
        set_var vault_jellyfin_password "$jf_pass" || true
        CHANGED=true
    else
        echo "  Jellyfin credentials: (exist, skipping)"
    fi
}

generate_semaphore() {
    echo ""
    echo "=== Automation Stack (Semaphore) ==="
    echo ""

    if ! var_needs_value vault_semaphore_db_password; then
        echo "  Semaphore credentials: (exist, skipping)"
        return
    fi

    # Reuse LE email for admin email if available
    local admin_email
    admin_email=$(get_var vault_le_email 2>/dev/null || echo "admin@localhost")
    if [[ -z "$admin_email" ]] || [[ "$admin_email" == REPLACE_* ]]; then
        admin_email="admin@localhost"
    fi

    local db_pass admin_pass secret_key
    db_pass=$(generate_password 32)
    admin_pass=$(generate_password 24)
    secret_key=$(generate_password 32)

    set_var vault_semaphore_admin_user "admin" || true
    set_var vault_semaphore_admin_name "Admin" || true
    set_var vault_semaphore_admin_email "$admin_email" || true
    set_var vault_semaphore_admin_password "$admin_pass" || true
    set_var vault_semaphore_db_password "$db_pass" || true
    set_var vault_semaphore_secret_key "$secret_key" || true
    CHANGED=true

    echo "  Semaphore:"
    echo "    Admin user:     admin"
    echo "    Admin email:    ${admin_email}"
    echo "    Admin password: ${admin_pass}"
    echo "    DB password:    (saved to vault)"
    echo "    Secret key:     (saved to vault)"
    echo ""
    echo "  Save the admin password — it is only shown once."
    echo ""
}

# --- Main ---

case "$STACK" in
    common)      generate_common ;;
    networking)  generate_networking ;;
    management)  generate_management ;;
    media)       generate_media ;;
    semaphore)   generate_semaphore ;;
    all)
        generate_common
        generate_networking
        generate_management
        generate_media
        generate_semaphore
        ;;
    *)
        echo "Unknown stack: ${STACK}"
        echo "Available: common, networking, management, media, semaphore, all"
        exit 1
        ;;
esac

if [ "$CHANGED" = false ]; then
    echo ""
    echo "No changes — all credentials already exist."
    exit 0
fi

# Re-encrypt vault with updated values
ansible-vault encrypt "$TMPFILE" --vault-password-file="$VAULT_PASS_FILE" --output="$VAULT_FILE"

echo ""
echo "Credentials saved to vault."
echo "Next steps:"
echo "  make ansible-sync      # regenerate .env files"
echo "  make deploy-all        # deploy stacks"
