- name: Configure HomeLab services
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - group_vars/all/vault.yml
  roles:
    - role: env_files
    - role: qbittorrent
    - role: prowlarr
    - role: sonarr
    - role: radarr
    - role: jellyseerr
    - role: recyclarr
    - role: adguard
    - role: traefik
    - role: uptime_kuma
